const sampleBuses = [{ id: 'bus-01', registration_no: 'NB-4521', lat: 6.5224, lng: 80.1141, speed: 32, next_stop: 'Neboda' }];
const routePoints = [[6.514, 80.08], [6.5224, 80.1141], [6.5318, 80.1297], [6.537, 80.15], [6.544, 80.18]];
const routes = [['Colombo', 'Kandy', '06:30 AM', '10:45 AM', '4h 15m', '18 seats', 'LKR 1,250'], ['Colombo', 'Galle', '08:15 AM', '10:55 AM', '2h 40m', '24 seats', 'LKR 850'], ['Kandy', 'Ella', '07:00 AM', '10:30 AM', '3h 30m', '9 seats', 'LKR 1,100'], ['Colombo', 'Jaffna', '09:30 PM', '05:45 AM', '8h 15m', '31 seats', 'LKR 2,450']];
const nav = document.querySelector('.app-nav nav');
const navStyle = document.createElement('style');
navStyle.textContent = '.app-nav{position:sticky!important;top:14px!important;z-index:1000!important}.app-nav nav{gap:18px}.app-nav nav .role-link{padding:8px 10px;color:#1557d6;background:#edf4ff;border-radius:999px;font-size:11px}.app-nav nav .driver-link{color:#071b4d;background:#ffc107}.app-nav nav .role-link:after{display:none}.app-nav nav a.active{color:#071b4d}.app-nav nav a.active:after{width:18px;height:3px;margin:7px auto 0;border-radius:2px;background:#ffc107}.app-nav nav .role-link.active:after{display:none}@media(max-width:1100px){.app-nav nav{gap:10px}.app-nav nav a{font-size:11px}}';
document.head.append(navStyle);
nav.insertAdjacentHTML('beforeend', '<a class="role-link" href="scan.html">Scan QR</a><a class="role-link driver-link" href="driver.html">Driver Portal</a>');
const sections = [...document.querySelectorAll('main section[id], footer[id]')];
const navLinks = [...nav.querySelectorAll('a[href^="#"]')];
function updateActiveNav() { const current = sections.reduce((active, section) => section.getBoundingClientRect().top <= 150 ? section : active, sections[0]); navLinks.forEach(link => link.classList.toggle('active', current && link.getAttribute('href') === `#${current.id}`)); }
window.addEventListener('scroll', updateActiveNav, { passive: true });
function feedback(text) { const element = document.querySelector('#search-feedback'); element.textContent = text; element.classList.add('visible'); }
const routeList = document.querySelector('#route-list');
function renderRoutes(list = routes) { routeList.innerHTML = list.map((route, index) => `<article class="route-card glass-card"><div class="route-card-top"><span class="route-number">0${index + 1}</span><span class="route-duration">◷ ${route[4]}</span></div><div class="route-points"><div><small>DEPARTURE</small><strong>${route[0]}</strong><b>${route[2]}</b></div><span class="route-arrow">→</span><div><small>ARRIVAL</small><strong>${route[1]}</strong><b>${route[3]}</b></div></div><div class="route-card-bottom"><span>▣ ${route[5]}</span><strong>from ${route[6]}</strong><button class="outline-button view-route" data-route="${route[0]} to ${route[1]}">View Route ↗</button></div></article>`).join(''); document.querySelectorAll('.view-route').forEach(button => button.onclick = () => { const parts = button.dataset.route.split(' to '); document.querySelector('#from-city').value = parts[0]; document.querySelector('#to-city').value = parts[1]; document.querySelector('#home').scrollIntoView({ behavior: 'smooth' }); feedback(`Ready to search ${button.dataset.route}.`); }); }
renderRoutes();
const map = L.map('map', { zoomControl: false, attributionControl: false }).setView([6.53, 80.125], 13); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map); L.polyline(routePoints, { color: '#1557D6', weight: 4, opacity: .9, dashArray: '8 9' }).addTo(map); const markers = {};
function renderBuses(buses) { buses.forEach(bus => { if (!markers[bus.id]) markers[bus.id] = L.marker([bus.lat, bus.lng], { icon: L.divIcon({ className: '', html: '<div class="bus-pin"><span>●</span></div>', iconSize: [38, 38], iconAnchor: [19, 19] }) }).addTo(map).bindPopup(`<b>${bus.registration_no}</b><br>${bus.speed} km/h · ${bus.next_stop}`); else markers[bus.id].setLatLng([bus.lat, bus.lng]); }); }
renderBuses(sampleBuses); document.querySelector('#center-map').onclick = () => map.fitBounds(L.latLngBounds(routePoints), { padding: [30, 30] }); document.querySelector('#swap-cities').onclick = () => { const from = document.querySelector('#from-city'), to = document.querySelector('#to-city'); [from.value, to.value] = [to.value, from.value]; };
document.querySelector('#search-form').onsubmit = event => { event.preventDefault(); const from = document.querySelector('#from-city').value, to = document.querySelector('#to-city').value; if (from === to) { feedback('Choose two different cities.'); return; } const results = routes.filter(route => route[0] === from && route[1] === to); renderRoutes(results.length ? results : routes); feedback(results.length ? `${results.length} bus option found from ${from} to ${to}.` : `Showing popular options. New ${from} to ${to} trips coming soon.`); document.querySelector('#routes').scrollIntoView({ behavior: 'smooth' }); };
document.querySelector('.menu-button').onclick = () => nav.classList.toggle('open');
function openTicket() { const modal = document.createElement('div'); modal.className = 'ticket-modal'; modal.innerHTML = '<div class="ticket-modal-card"><button class="modal-close" aria-label="Close checkout">×</button><span class="kicker">DEMO CHECKOUT</span><h2>Secure your seat</h2><p>Test payment only. No real money is charged.</p><label class="demo-card-field">TEST CARD NUMBER<input value="4242 4242 4242 4242" readonly></label><button class="ticket-button demo-pay">Pay LKR 1,250</button><div class="payment-result" hidden><span class="payment-check">✓</span><h3>Payment successful</h3><p>Your digital ticket is ready.</p><canvas class="ticket-qr"></canvas><strong>BG-82491</strong><small>Colombo to Kandy · Seat 12A</small><a class="ticket-button download-ticket" download="busgo-ticket.txt" href="data:text/plain;charset=utf-8,BusGo%20Ticket%20BG-82491%20-%20Colombo%20to%20Kandy%20-%20Seat%2012A">Download ticket</a></div></div>'; document.body.append(modal); modal.querySelector('.modal-close').onclick = () => modal.remove(); const pay = modal.querySelector('.demo-pay'); pay.onclick = () => { pay.textContent = 'Processing...'; pay.disabled = true; setTimeout(() => { pay.hidden = true; const result = modal.querySelector('.payment-result'); result.hidden = false; const draw = () => QRCode.toCanvas(result.querySelector('canvas'), 'BUSGO|BG-82491|COLOMBO-KANDY|SEAT-12A', { width: 170, margin: 2 }); if (window.QRCode) draw(); else { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/qrcode@1.5.3/build/qrcode.min.js'; script.onload = draw; document.head.append(script); } }, 2000); }; }
document.querySelector('#ticket-button').onclick = openTicket;
function connectRealtime() { if (!BUSGO_CONFIG.supabaseUrl || !BUSGO_CONFIG.supabaseAnonKey) return; const client = supabase.createClient(BUSGO_CONFIG.supabaseUrl, BUSGO_CONFIG.supabaseAnonKey); client.from('buses').select('*').then(({ data }) => { if (data?.length) renderBuses(data); }); client.channel('buses-live').on('postgres_changes', { event: '*', schema: 'public', table: 'buses' }, payload => renderBuses([payload.new])).subscribe(); }
connectRealtime(); updateActiveNav(); if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('sw.js'));
