-- BusGo production-safe Supabase setup for the free tier.
-- Create driver users in Authentication > Users first, then assign their UUID below.
create table if not exists public.buses (
  id text primary key,
  driver_id uuid references auth.users(id),
  registration_no text not null,
  route_label text not null default 'Matugama to Aluthgama',
  lat double precision not null,
  lng double precision not null,
  speed numeric not null default 0,
  heading numeric not null default 0,
  status text not null default 'stopped',
  next_stop text default 'Route stop',
  eta text default '-',
  updated_at timestamptz not null default now()
);
alter table public.buses add column if not exists driver_id uuid references auth.users(id);
alter table public.buses enable row level security;

drop policy if exists "Public can read bus locations" on public.buses;
drop policy if exists "Drivers can update bus locations" on public.buses;
drop policy if exists "Drivers can update existing locations" on public.buses;
drop policy if exists "Authenticated drivers can insert assigned buses" on public.buses;
drop policy if exists "Drivers can update their assigned bus" on public.buses;

create policy "Public can read bus locations"
on public.buses for select
using (true);

create policy "Authenticated drivers can insert assigned buses"
on public.buses for insert to authenticated
with check (driver_id = (select auth.uid()));

create policy "Drivers can update their assigned bus"
on public.buses for update to authenticated
using (driver_id = (select auth.uid()))
with check (driver_id = (select auth.uid()));

do $$
begin
  if not exists (
    select 1
    from pg_publication_rel pr
    join pg_class c on c.oid = pr.prrelid
    join pg_namespace n on n.oid = c.relnamespace
    join pg_publication p on p.oid = pr.prpubid
    where p.pubname = 'supabase_realtime'
      and n.nspname = 'public'
      and c.relname = 'buses'
  ) then
    alter publication supabase_realtime add table public.buses;
  end if;
end
$$;

-- After creating a driver in Supabase Auth, assign a bus:
-- update public.buses set driver_id = 'DRIVER_AUTH_USER_UUID' where id = 'bus-01';
-- update public.buses set driver_id = 'DRIVER_AUTH_USER_UUID' where id = 'bus-02';

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  origin text not null,
  destination text not null,
  departure_time text not null,
  arrival_time text not null,
  duration text not null,
  available_seats integer not null default 0,
  price numeric not null default 0,
  created_at timestamptz not null default now()
);
alter table public.routes enable row level security;
drop policy if exists "Public can read routes" on public.routes;
create policy "Public can read routes" on public.routes for select using (true);

create table if not exists public.bookings (
  id text primary key,
  route_id bigint references public.routes(id),
  passenger_id uuid references auth.users(id),
  passenger_count integer not null default 1,
  seat_number text not null,
  status text not null default 'confirmed',
  created_at timestamptz not null default now()
);
alter table public.bookings enable row level security;
drop policy if exists "Passengers can read own bookings" on public.bookings;
drop policy if exists "Passengers can create own bookings" on public.bookings;
create policy "Passengers can read own bookings" on public.bookings for select to authenticated using (passenger_id = (select auth.uid()));
create policy "Passengers can create own bookings" on public.bookings for insert to authenticated with check (passenger_id = (select auth.uid()));
